name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Set up Go 1.x
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: |
          go test -v ./...
      - name: Test
        run: |
          go test -v ./...
        working-directory: testdata/gqlgen-todos
